(()=>{'use strict';const M=DiceGame,$=id=>document.getElementById(id),KEY='truefire-dice-m05-1';let seed=Date.now()>>>0,g,selectedDie=0,selectedCard=null,mode='offer',auto=true,observe=false,timer,error='';
try{let saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&saved.version==='M0.5'&&!M.check(saved).length)g=saved;}catch{}if(!g)g=M.create(seed);
const node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const human=()=>g.phase==='play'&&g.actor===0&&!observe;
const seatName=s=>g.seats[s]?M.GODS[g.seats[s].god].name:'空座';
function describe(a){const die='骰'+(a.d+1);if(a.type==='offer')return die+'供奉'+seatName(a.s);if(a.type==='contest')return '两骰改写'+seatName(a.s);if(a.type==='protect')return '永久失去所选记忆，守护'+seatName(a.s);if(a.type!=='power')return a.type;
 const name=M.GODS[a.god].name,power=M.GODS[a.god].power;
 if(power==='move')return '把'+seatName(a.s)+'的'+M.E[M.GODS[g.seats[a.s].god].elements[a.k]]+'供奉移到'+seatName(a.target);
 if(power==='swap')return '交换'+seatName(a.s)+'的'+M.E[M.GODS[g.seats[a.s].god].elements[a.k]]+'与'+seatName(a.target)+'的'+M.E[M.GODS[g.seats[a.target].god].elements[a.slot]]+'供奉归属';
 if(power==='rain')return '侵蚀从'+seatName(a.s)+'移到'+seatName(a.target)+(g.seats[a.target].weather===2?'（将毁座）':'');
 if(power==='cool')return '为'+seatName(a.s)+'移除1侵蚀';if(power==='contest')return '一骰改写'+seatName(a.s)+'的'+M.E[M.GODS[g.seats[a.s].god].elements[a.k]];
 if(power==='recover')return '取回'+M.E[g.players[g.actor].discard.find(c=>c.id===a.card).e]+'记忆';if(power==='hunt')return '重掷骰'+(a.other+1)+'，想起一张';return '想起两张';}
function apply(a){try{const oldTurn=g.turn;M.act(g,a);const errors=M.check(g);if(errors.length)throw Error(errors.join('、'));error='';if(g.turn!==oldTurn){selectedDie=0;selectedCard=null;mode='offer';}if(g.dice[selectedDie]?.used)selectedDie=g.dice.findIndex(d=>!d.used);if(!g.players[0].hand.some(c=>c.id===selectedCard))selectedCard=null;}catch(e){error=e.message;auto=false;observe=false;}render();}
function render(){const openGifts=new Set([...document.querySelectorAll('.gift[open]')].map(e=>e.dataset.god));const openPlayers=new Set([...document.querySelectorAll('.player details[open]')].map(e=>e.dataset.player));clearTimeout(timer);try{localStorage.setItem(KEY,JSON.stringify(g));}catch{error='浏览器未允许保存；本局可继续，刷新会重开。';}const legal=M.legal(g),p=g.players[0],turn=g.players[g.actor],can=human(),unused=g.dice.filter(d=>!d.used).length,card=p.hand.find(c=>c.id===selectedCard);const selected=g.dice[selectedDie];const validDie=!!selected&&!selected.used;
 $('round').textContent='第 '+g.round+' / 6 更 · '+(g.phase==='ended'?'已结束':turn.name+'的回合');$('goal').textContent='已留下 '+g.saved.length+' / 4 个名字 · 另有 '+g.ruined.length+' 尊毁座';
 $('status').textContent=error||(g.phase==='ended'?'这一夜已落定。':can?'轮到你：骰子已掷好，选择怎样使用。':auto||observe?'对手正在思考……':'对手已暂停，点「让对手行动一步」继续。');
 $('players').replaceChildren(...g.players.map((p,i)=>{const e=node('div',undefined,'player'+(g.actor===i&&g.phase==='play'?' active':''));e.append(node('strong',p.name+' · '+p.score+'分'),node('small','手中'+p.hand.length+'张 · 永久失去'+p.forgotten.length+'张'),node('small','神明记忆：'+(p.gifts.map(id=>M.GODS[id].name).join('、')||'尚无')));const zones=node('details');zones.dataset.player=String(i);zones.open=openPlayers.has(String(i));zones.append(node('summary','查看公开记忆'),node('small','暂忘：'+(p.discard.map(c=>M.E[c.e]).join('、')||'无')),node('small','永久失去：'+(p.forgotten.map(c=>M.E[c.e]).join('、')||'无')));e.append(zones);return e;}));
 document.querySelector('.turn').hidden=g.phase==='ended';
 $('turnTitle').textContent=can?'你的两颗骰子':g.phase==='ended'?'骰子已收起':turn.name+'的两颗骰子';$('budget').textContent=(g.placed?'供奉已改变':'可改变一次供奉')+' · '+(g.usedPower?'已回想':'可回想一次');
 $('dice').replaceChildren(...g.dice.map((d,i)=>{const b=node('button',undefined,'die');b.append(node('small','骰 '+(i+1)+' · '+(d.face+1)+'点'),node('strong',M.E[d.face]),node('small',d.used?'已使用':'可使用'));b.disabled=!can||d.used;b.setAttribute('aria-label','骰'+(i+1)+'：'+M.E[d.face]+(d.used?'，已使用':''));b.setAttribute('aria-pressed',String(i===selectedDie));b.onclick=()=>{selectedDie=i;render();};return b;}));
 $('modes').replaceChildren(...[['offer','供奉'],['contest','争夺 · 两骰'],['protect','守护 · 燃忆']].map(([value,label])=>{const b=node('button',label);b.disabled=!can||!unused||(value==='offer'&&g.placed)||(value==='contest'&&(g.placed||unused<2))||(value==='protect'&&(!p.hand.length||!g.seats.some(s=>s&&s.weather>0)));b.setAttribute('aria-pressed',String(mode===value));b.onclick=()=>{mode=value;render();};return b;}));
 $('hand').replaceChildren(...p.hand.map(c=>{const b=node('button',M.E[c.e]);b.disabled=!can;b.setAttribute('aria-label',M.E[c.e]+'记忆');b.setAttribute('aria-pressed',String(selectedCard===c.id));b.onclick=()=>{selectedCard=selectedCard===c.id?null:c.id;render();};return b;}));
 $('piles').textContent='待想起 '+p.deck.length+' · 暂忘 '+p.discard.length+' · 永久失去 '+p.forgotten.length;
 const correction=legal.find(a=>a.type==='correct'&&a.d===selectedDie&&a.card===selectedCard);$('correct').disabled=!can||!correction;$('correct').onclick=()=>apply(correction);
 const recall=legal.find(a=>a.type==='recall'&&a.d===selectedDie);$('recall').disabled=!can||!recall;$('recall').onclick=()=>apply(recall);$('end').disabled=!can;$('end').onclick=()=>apply({type:'end'});
 const targets=legal.filter(a=>a.type===mode&&a.d===selectedDie&&(mode!=='protect'||a.card===selectedCard));
 let hint=g.phase==='ended'?'本局已经结算。':!can?'等待你的回合。':!unused?'两颗骰子都已用完，结束回合即可。':!validDie?'先选择一颗未使用的骰子。':mode==='protect'?(!g.seats.some(s=>s&&s.weather>0)?'目前没有侵蚀，无需守护。':!p.hand.length?'没有手牌，无法支付永久遗忘。':!card?'选择一张愿意永久失去的手牌，再点神座下的守护。':'将永久失去'+M.E[card.e]+'记忆，支付骰'+(selectedDie+1)+'；可守护'+targets.length+'尊神。'):g.placed?'供奉已经改变过；剩下的骰子可寻忆、守护或回想。':mode==='contest'&&unused<2?'争夺需要两颗未使用的骰子。':targets.length?'骰'+(selectedDie+1)+' · '+M.E[selected.face]+'，可'+(mode==='contest'?'争夺':'供奉')+targets.length+'处；点击亮起的槽位。':mode==='contest'?'此骰没有匹配的对手供奉。可换骰、改骰，或改选供奉。':'此骰没有匹配的空槽。可换另一骰、用记忆改骰，或寻忆。';
 $('selection').textContent=hint;$('targetHint').textContent=hint;$('backToDice').hidden=g.phase==='ended';
 $('correct').textContent=card&&validDie?'暂忘'+M.E[card.e]+' → 骰'+(selectedDie+1)+'改为'+M.E[card.e]:'弃所选记忆，改所选骰';
 $('end').textContent=can&&unused?'结束回合 · 放弃'+unused+'骰':'结束回合';

 $('reserve').textContent=g.phase==='ended'?'这一夜已经结束；尚在座上的神不计入唤醒。':'候场 '+g.queue.length+' 尊 · 填满即唤醒，每更末侵蚀＋1';
 $('gods').replaceChildren(...g.seats.map((s,index)=>{const e=node('article',undefined,'god');if(!s){e.append(node('h3','火塘空位'),node('p','候场神牌已用完。'));return e;}const god=M.GODS[s.god],img=node('img');img.src=god.image;img.alt=god.name+'完整插画';e.append(img,node('small',god.culture+' · '+god.original),node('h3',god.name),node('p',god.verse),node('p','侵蚀 '+s.weather+' / 3'+(s.weather===2&&g.phase==='play'?' · 本更末将毁座':''),'weather'+(s.weather===2?' danger':'')));let slots=node('div',undefined,'slots');
 s.slots.forEach((owner,k)=>{const b=node('button',undefined,'slot');b.dataset.owner=owner===null?'':owner;b.append(node('strong',M.E[god.elements[k]]),node('small',owner===null?'空槽':g.players[owner].name));const a=legal.find(a=>a.type===mode&&['offer','contest'].includes(mode)&&a.d===selectedDie&&a.s===index&&a.k===k);b.disabled=!can||!a;if(can&&a)b.classList.add('available');b.setAttribute('aria-label',god.name+' '+M.E[god.elements[k]]+' '+(owner===null?'空槽':g.players[owner].name+'的供奉'));b.onclick=()=>apply(a);slots.append(b);});e.append(slots);const complete=can&&mode==='offer'&&s.slots.filter(v=>v!==null).length===2&&legal.some(a=>a.type==='offer'&&a.d===selectedDie&&a.s===index);if(complete){const counts=g.players.map((_,i)=>s.slots.filter(v=>v===i).length+(i===g.actor?1:0)),winner=counts.findIndex(n=>n>=2);e.append(node('p',winner<0?'填满后：各得1分，你收下神明记忆。':'填满后：'+g.players[winner].name+'得5分与神明记忆'+(winner!==g.actor?'，你得1分':'')+'。','outcome'));}
 if(mode==='protect'){const a=legal.find(a=>a.type==='protect'&&a.d===selectedDie&&a.card===selectedCard&&a.s===index),b=node('button',card?'永久失去'+M.E[card.e]+' · 侵蚀−'+Math.min(2,s.weather):'先选一张要燃掉的记忆','protect');b.disabled=!can||!a;b.onclick=()=>apply(a);e.append(b);}e.append(node('p','记住后 · '+god.effect,'power'));return e;}));
 $('gifts').replaceChildren(...p.gifts.map(id=>{const e=node('details',undefined,'gift');e.dataset.god=String(id);e.open=openGifts.has(String(id));e.append(node('summary',M.GODS[id].name),node('p',M.GODS[id].effect));const options=legal.filter(a=>a.type==='power'&&a.god===id&&a.d===selectedDie);if(!options.length)e.append(node('p',g.usedPower?'本回合已回想过。':'当前没有可用目标，或尚未选中未使用的骰子。','help'));for(const a of options){const b=node('button','骰'+(a.d+1)+' · '+describe(a));b.disabled=!can;b.onclick=()=>apply(a);e.append(b);}return e;}));if(!p.gifts.length)$('gifts').append(node('p','唤醒后，神牌会来到这里，成为可反复回想的记忆。','help'));
 $('latest').textContent=g.events.at(-1)?.text||'';
 $('events').replaceChildren(...g.events.slice().reverse().map(e=>node('li','第'+e.round+'更 · '+e.text)));
 $('result').hidden=g.phase!=='ended';if(g.phase==='ended'){let high=Math.max(...g.players.map(p=>p.score));$('result').replaceChildren(node('h2',g.failed?'名字留得太少，这一夜共同失败':g.players.filter(p=>p.score===high).map(p=>p.name).join('、')+'守住了最多记忆'),node('p','唤醒 '+g.saved.length+' / 8 尊；毁座 '+g.ruined.length+' 尊。'+(g.failed?'个人得分仅作记录。':g.players.filter(p=>p.score===high).length>1?'最高分相同，共同获胜。':'最高分者获胜。')),node('p','已留下：'+(g.saved.map(id=>M.GODS[id].name).join('、')||'无')));}
 $('auto').textContent='对手自动行动：'+(auto?'开':'关');$('auto').setAttribute('aria-pressed',String(auto));$('observe').textContent=observe?'接回自己的回合':'旁观整局';$('observe').setAttribute('aria-pressed',String(observe));$('step').disabled=g.phase==='ended'||g.actor===0;$('observe').disabled=g.phase==='ended';
 if(g.phase==='play'&&(observe||(g.actor!==0&&auto)))timer=setTimeout(()=>apply(M.choose(g)),650);
}
$('auto').onclick=()=>{auto=!auto;render();};$('step').onclick=()=>{if(g.actor!==0&&g.phase==='play')apply(M.choose(g));};$('observe').onclick=()=>{observe=!observe;render();};$('new').onclick=()=>{if(!confirm('放下本局，重新掷骰守夜？'))return;clearTimeout(timer);g=M.create(++seed);selectedDie=0;selectedCard=null;observe=false;error='';render();};render();})();
